---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      provider: parallels
  - name: centos-7.1
    driver:
      provider: parallels

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[chefpoc-users::default]
    attributes:
      users: "tester"
      user:
        ssh_keygen: "false"
