---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[chefpoc-users::default]
    attributes:
      users: "tester"
      user:
        ssh_keygen: "false"
