---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chefpoc-zookeeper::default]
    attributes:
