---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: debian-7.11

suites:
  - name: default
    run_list:
      - recipe[chefpoc-base::default]
    attributes:
  - name: chef-client
    run_list:
      - recipe[chefpoc-base::chef-client]
  - name: cron
    run_list:
      - recipe[chefpoc-base::cron]
  - name: firewall
    run_list:
      - recipe[chefpoc-base::firewall]
  - name: ntp
    run_list:
      - recipe[chefpoc-base::ntp]
  - name: openssh
    run_list:
      - recipe[chefpoc-base::openssh]
  - name: packages
    run_list:
      - recipe[chefpoc-base::packages]
  - name: postfix
    run_list:
      - recipe[chefpoc-base::postfix]
  - name: rsyslog
    run_list:
      - recipe[chefpoc-base::rsyslog]
  - name: selinux
    run_list:
      - recipe[chefpoc-base::selinux]
  - name: sysctl
    run_list:
      - recipe[chefpoc-base::sysctl]
